//! Postgres-dialect SQL code generation.
//!
//! For each schema, we emit a `CREATE TABLE` with columns mapped from CSL primitives,
//! indexes for `@indexed`/`@unique`/`@searchable` fields, and foreign-key constraints
//! for `Ref<T>` fields. `@chunked` fields live in a separate `*_chunk` table with a
//! composite key `(parent_id, chunk_idx)`.
//!
//! This module emits forward migrations only. Downgrade migrations are produced by
//! a sibling function that diffs two schema versions — not shown here.

use crate::ast::{FieldDecl, PrimitiveType, SchemaDecl, TypeExpr};
use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit a single SQL string containing all schemas' DDL, in declaration order.
///
/// # Errors
/// Returns a [`CslError::Codegen`] if an unsupported type appears.
pub fn emit_sql(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    out.push_str("-- Generated by signet-csl. Do not edit manually.\n");
    if !typed.namespace.is_empty() {
        out.push_str(&format!("-- namespace: {}\n", typed.namespace));
    }
    out.push_str("SET statement_timeout = '60s';\n\n");

    for name in &typed.decl_order {
        let Some(schema) = typed.schemas.get(name) else {
            continue;
        };
        emit_schema(&schema.decl, &mut out)?;
        out.push('\n');
    }
    Ok(out)
}

fn emit_schema(schema: &SchemaDecl, out: &mut String) -> CslResult<()> {
    let table = table_name(&schema.name);
    out.push_str(&format!("CREATE TABLE IF NOT EXISTS {table} (\n"));

    // Emit columns.
    let mut column_lines: Vec<String> = Vec::new();
    for f in &schema.fields {
        // Skip fields that live in a separate chunk table.
        if is_chunked(f) {
            continue;
        }
        let sql_type = map_type(&f.ty);
        let nullable = if f.ty.is_optional() { "" } else { " NOT NULL" };
        let mut line = format!("  {name} {ty}{null}", name = f.name, ty = sql_type, null = nullable);

        if f.decorators.iter().any(|d| d.is("primary")) {
            line.push_str(" PRIMARY KEY");
        }
        if f.decorators.iter().any(|d| d.is("unique")) && !f.decorators.iter().any(|d| d.is("primary")) {
            line.push_str(" UNIQUE");
        }
        column_lines.push(line);
    }

    // Convention: every CSL-generated table carries a `tenant` text column for
    // multi-tenant isolation at retrieval time. Empty string means "default
    // tenant" (single-tenant deployments).
    if !schema.fields.iter().any(|f| f.name == "tenant") {
        column_lines.push("  tenant text NOT NULL DEFAULT ''".to_string());
    }

    // Emit foreign keys for Ref<T> fields.
    for f in &schema.fields {
        if let TypeExpr::Ref(target, _) = &f.ty {
            let line = format!(
                "  FOREIGN KEY ({name}) REFERENCES {target_table} (id)",
                name = f.name,
                target_table = table_name(target),
            );
            column_lines.push(line);
        }
    }

    out.push_str(&column_lines.join(",\n"));
    out.push_str("\n);\n");

    // Tenant scoping index (matches the retrieval layer's `coalesce(tenant,'') = $N`).
    out.push_str(&format!(
        "CREATE INDEX IF NOT EXISTS {table}_tenant_idx ON {table} (tenant);\n",
    ));

    // Indexes.
    for f in &schema.fields {
        if f.decorators.iter().any(|d| d.is("indexed")) {
            out.push_str(&format!(
                "CREATE INDEX IF NOT EXISTS {idx} ON {table} ({col});\n",
                idx = format!("{table}_{col}_idx", table = table, col = f.name),
                col = f.name,
            ));
        }
        if f.decorators.iter().any(|d| d.is("searchable")) {
            out.push_str(&format!(
                "CREATE INDEX IF NOT EXISTS {idx} ON {table} USING gin (to_tsvector('english', {col}));\n",
                idx = format!("{table}_{col}_fts_idx", table = table, col = f.name),
                col = f.name,
            ));
        }
    }

    // Chunk table for any @chunked field.
    if schema.fields.iter().any(is_chunked) {
        let chunk_table = format!("{table}_chunk");
        out.push_str(&format!(
            "CREATE TABLE IF NOT EXISTS {chunk_table} (\n\
             \x20\x20parent_id  bytea NOT NULL REFERENCES {table}(id) ON DELETE CASCADE,\n\
             \x20\x20chunk_idx  integer NOT NULL,\n\
             \x20\x20content    text NOT NULL,\n\
             \x20\x20metadata   jsonb NOT NULL DEFAULT '{{}}'::jsonb,\n\
             \x20\x20PRIMARY KEY (parent_id, chunk_idx)\n\
             );\n",
        ));
    }

    Ok(())
}

fn is_chunked(f: &FieldDecl) -> bool {
    f.decorators.iter().any(|d| d.is("chunked"))
}

fn table_name(schema_name: &str) -> String {
    // lower_snake_case
    let mut out = String::with_capacity(schema_name.len() + 2);
    for (i, c) in schema_name.chars().enumerate() {
        if c.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

fn map_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Optional(inner, _) => map_type(inner),
        TypeExpr::Primitive(p, _) => map_primitive(*p).to_owned(),
        TypeExpr::Ref(_, _) => "bytea".to_owned(), // FK column type mirrors Ulid representation
        TypeExpr::Vector(_, _) => "bytea".to_owned(), // vectors live in the vector store, placeholder
        TypeExpr::List(_, _) => "jsonb".to_owned(),
        TypeExpr::Map(_, _, _) => "jsonb".to_owned(),
        TypeExpr::Named(_, _) => "text".to_owned(), // enums rendered as text for now
    }
}

fn map_primitive(p: PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::String | PrimitiveType::Text => "text",
        PrimitiveType::Ulid => "bytea",
        PrimitiveType::Uuid => "uuid",
        PrimitiveType::I32 => "integer",
        PrimitiveType::I64 => "bigint",
        PrimitiveType::F32 => "real",
        PrimitiveType::F64 => "double precision",
        PrimitiveType::Bool => "boolean",
        PrimitiveType::Instant => "timestamptz",
        PrimitiveType::Duration => "interval",
        PrimitiveType::Json => "jsonb",
    }
}
