//! Python TypedDict codegen.
//!
//! Emits a single `generated.py` file containing one `class <Schema>(TypedDict)`
//! (or functional-form equivalent for keyword-colliding field names) +
//! one `<SCHEMA>_META: Final` + one `<Enum> = Literal[...]` per declaration.
//! See `docs/superpowers/specs/2026-04-21-csl-codegen-python-design.md`
//! for the shape decisions.

use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit the full Python module text for a typed CSL file.
///
/// # Errors
///
/// Returns [`crate::error::CslError::Codegen`] for an unsupported AST shape
/// (e.g., `Map<K, V>` fields, or a `tenant` field with a non-String type).
pub fn emit_python(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    emit_file_header(&mut out);
    let mut enum_names: Vec<&String> = typed.enums.keys().collect();
    enum_names.sort();
    for name in enum_names {
        if let Some(en) = typed.enums.get(name) {
            emit_enum(&mut out, en);
        }
    }
    if !typed.enums.is_empty() {
        out.push('\n');
    }
    for name in &typed.decl_order {
        if let Some(schema) = typed.schemas.get(name) {
            emit_schema(&mut out, &schema.decl)?;
        }
    }
    Ok(out)
}

fn emit_file_header(out: &mut String) {
    out.push_str(
        "# Generated by `sealstack compile`. Do not edit.\n\
         # ruff: noqa\n\
         \n\
         from typing import Any, Final, Literal, NotRequired, TypedDict\n\
         \n",
    );
}

use crate::ast::{PrimitiveType, TypeExpr};
use crate::error::CslError;

/// Render a CSL type expression as a Python type annotation.
///
/// When `optional` is true AND `ty` is `Optional<inner>`, wraps the inner
/// render in `NotRequired[...]`. Any other call produces the direct render
/// without optional-wrapping (e.g., `T` for `Optional<T>` with `optional=false`,
/// or `T[]` for `List<T>` regardless).
fn render_field_type(ty: &TypeExpr, optional: bool) -> CslResult<String> {
    match ty {
        TypeExpr::Primitive(p, _) => Ok(render_primitive(*p).to_string()),
        TypeExpr::Ref(_, _) => Ok("str".to_string()),
        TypeExpr::Named(name, _) => Ok(name.clone()),
        TypeExpr::Optional(inner, _) => {
            let inner_str = render_field_type(inner, false)?;
            if optional {
                Ok(format!("NotRequired[{inner_str}]"))
            } else {
                Ok(inner_str)
            }
        }
        TypeExpr::List(inner, _) => Ok(format!("list[{}]", render_field_type(inner, false)?)),
        TypeExpr::Vector(_, _) => Err(CslError::Codegen {
            message: "Vector<N> reached render_field_type; callers must filter vector fields before rendering them (see emit_schema's is_vector guard)".into(),
        }),
        TypeExpr::Map(_, _, _) => Err(CslError::Codegen {
            message: "Map<K, V> fields are not supported in Python codegen (type checker should have rejected this)".into(),
        }),
    }
}

fn render_primitive(p: PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::String | PrimitiveType::Text => "str",
        PrimitiveType::Ulid | PrimitiveType::Uuid => "str",
        PrimitiveType::I32 | PrimitiveType::I64 => "int",
        PrimitiveType::F32 | PrimitiveType::F64 => "float",
        PrimitiveType::Bool => "bool",
        PrimitiveType::Instant | PrimitiveType::Duration => "str",
        PrimitiveType::Json => "Any",
    }
}

fn emit_enum(out: &mut String, en: &crate::ast::EnumDecl) {
    out.push_str(&format!("{} = Literal[", en.name));
    let mut first = true;
    for v in &en.variants {
        if !first {
            out.push_str(", ");
        }
        first = false;
        let wire = v
            .wire
            .clone()
            .unwrap_or_else(|| v.name.to_ascii_lowercase());
        out.push('"');
        out.push_str(&escape_wire(&wire));
        out.push('"');
    }
    out.push_str("]\n");
}

fn escape_wire(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn emit_schema(out: &mut String, decl: &crate::ast::SchemaDecl) -> CslResult<()> {
    // Functional-syntax fallback (Task T6) slots in here. For T4 we emit
    // the class form unconditionally; T6 flips the dispatch based on
    // needs_functional_syntax.
    emit_schema_class_form(out, decl)
}

fn emit_schema_class_form(out: &mut String, decl: &crate::ast::SchemaDecl) -> CslResult<()> {
    // Vector skip (both bare and optional-wrapped).
    let is_vector = |ty: &crate::ast::TypeExpr| -> bool {
        match ty {
            crate::ast::TypeExpr::Vector(_, _) => true,
            crate::ast::TypeExpr::Optional(inner, _) => {
                matches!(inner.as_ref(), crate::ast::TypeExpr::Vector(_, _))
            }
            _ => false,
        }
    };

    out.push_str(&format!("class {}(TypedDict):\n", decl.name));

    let mut emitted_tenant = false;
    let mut emitted_any_field = false;
    for field in &decl.fields {
        if is_vector(&field.ty) {
            continue;
        }

        if field.name == "tenant" {
            let is_string_or_text = matches!(
                &field.ty,
                crate::ast::TypeExpr::Primitive(
                    crate::ast::PrimitiveType::String | crate::ast::PrimitiveType::Text,
                    _,
                ),
            );
            if !is_string_or_text {
                return Err(CslError::Codegen {
                    message: format!(
                        "schema `{}` declares `tenant` field with non-String type; the tenant column is always `text` in SQL and the Python TypedDict must match (see spec §6)",
                        decl.name,
                    ),
                });
            }
            emitted_tenant = true;
        }

        let optional = matches!(field.ty, crate::ast::TypeExpr::Optional(_, _));
        let ty_str = render_field_type(&field.ty, optional)?;
        out.push_str(&format!("    {name}: {ty}\n", name = field.name, ty = ty_str));
        emitted_any_field = true;
    }

    if !emitted_tenant {
        out.push_str("    tenant: str\n");
        emitted_any_field = true;
    }

    // An empty TypedDict body would be a SyntaxError; `pass` is the Python
    // idiom. In practice every schema has at least a primary-key field,
    // so this is belt-and-braces.
    if !emitted_any_field {
        out.push_str("    pass\n");
    }

    out.push_str("\n");
    Ok(())
}

fn is_python_keyword(name: &str) -> bool {
    matches!(
        name,
        "False" | "None" | "True"
        | "and" | "as" | "assert" | "async" | "await"
        | "break" | "class" | "continue"
        | "def" | "del"
        | "elif" | "else" | "except"
        | "finally" | "for" | "from"
        | "global" | "if" | "import" | "in" | "is"
        | "lambda" | "nonlocal" | "not" | "or"
        | "pass" | "raise" | "return" | "try"
        | "while" | "with" | "yield"
        // Soft keywords in 3.10+ — treated as reserved for forward safety
        | "match" | "case"
    )
}

#[cfg(test)]
mod type_mapper_tests {
    use super::*;
    use crate::ast::{PrimitiveType, TypeExpr};
    use crate::span::Span;

    fn s() -> Span {
        Span::point(0)
    }

    #[test]
    fn primitives_map_to_default_types() {
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::String, s()), false).unwrap(), "str");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Text, s()), false).unwrap(), "str");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Ulid, s()), false).unwrap(), "str");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Uuid, s()), false).unwrap(), "str");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::I32, s()), false).unwrap(), "int");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::I64, s()), false).unwrap(), "int");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::F32, s()), false).unwrap(), "float");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::F64, s()), false).unwrap(), "float");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Bool, s()), false).unwrap(), "bool");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Instant, s()), false).unwrap(), "str");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Duration, s()), false).unwrap(), "str");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Json, s()), false).unwrap(), "Any");
    }

    #[test]
    fn ref_and_named_schema_render_as_str() {
        assert_eq!(render_field_type(&TypeExpr::Ref("User".into(), s()), false).unwrap(), "str");
    }

    #[test]
    fn named_enum_renders_as_identifier() {
        assert_eq!(render_field_type(&TypeExpr::Named("Tier".into(), s()), false).unwrap(), "Tier");
    }

    #[test]
    fn list_renders_lowercase_generic() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::String, s()));
        assert_eq!(render_field_type(&TypeExpr::List(inner, s()), false).unwrap(), "list[str]");
    }

    #[test]
    fn nested_list_renders_correctly() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::I32, s()));
        let outer = Box::new(TypeExpr::List(inner, s()));
        assert_eq!(render_field_type(&TypeExpr::List(outer, s()), false).unwrap(), "list[list[int]]");
    }

    #[test]
    fn optional_wrapper_uses_not_required() {
        // Case A: render_field_type called on the outer Optional with optional=true
        // (as emit_schema will do) -> inner type wrapped in NotRequired[...].
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::F32, s()));
        assert_eq!(
            render_field_type(&TypeExpr::Optional(inner, s()), true).unwrap(),
            "NotRequired[float]",
        );
    }

    #[test]
    fn optional_with_optional_false_unwraps_without_wrapping() {
        // Case B: defensive -- render_field_type can be called with optional=false
        // even on an Optional type (e.g., recursion from List<T?>). It should
        // return the inner type's render with no NotRequired wrapper.
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::F32, s()));
        assert_eq!(
            render_field_type(&TypeExpr::Optional(inner, s()), false).unwrap(),
            "float",
        );
    }

    #[test]
    fn vector_errors_at_render_time() {
        // Field-level code skips Vector before calling render. If it reaches here,
        // it's a caller-contract violation -- surface loudly (parity with TS emit).
        assert!(matches!(
            render_field_type(&TypeExpr::Vector(32, s()), false),
            Err(crate::error::CslError::Codegen { .. })
        ));
    }

    #[test]
    fn map_returns_codegen_error() {
        let k = Box::new(TypeExpr::Primitive(PrimitiveType::String, s()));
        let v = Box::new(TypeExpr::Primitive(PrimitiveType::I32, s()));
        assert!(matches!(
            render_field_type(&TypeExpr::Map(k, v, s()), false),
            Err(crate::error::CslError::Codegen { .. })
        ));
    }
}

#[cfg(test)]
mod enum_and_keyword_tests {
    use super::*;
    use crate::ast::{EnumDecl, EnumVariant};
    use crate::span::Span;

    fn s() -> Span {
        Span::point(0)
    }

    #[test]
    fn emit_enum_with_explicit_wire_forms() {
        let en = EnumDecl {
            name: "Tier".into(),
            variants: vec![
                EnumVariant { name: "Free".into(), wire: Some("free".into()), span: s() },
                EnumVariant { name: "Pro".into(), wire: Some("pro".into()), span: s() },
                EnumVariant { name: "Enterprise".into(), wire: Some("enterprise".into()), span: s() },
            ],
            span: s(),
        };
        let mut out = String::new();
        emit_enum(&mut out, &en);
        assert_eq!(out, "Tier = Literal[\"free\", \"pro\", \"enterprise\"]\n");
    }

    #[test]
    fn emit_enum_falls_back_to_lowercased_ident() {
        let en = EnumDecl {
            name: "Status".into(),
            variants: vec![
                EnumVariant { name: "Active".into(), wire: None, span: s() },
                EnumVariant { name: "Archived".into(), wire: None, span: s() },
            ],
            span: s(),
        };
        let mut out = String::new();
        emit_enum(&mut out, &en);
        assert_eq!(out, "Status = Literal[\"active\", \"archived\"]\n");
    }

    #[test]
    fn escape_wire_handles_backslash_and_double_quote() {
        assert_eq!(escape_wire("plain"), "plain");
        assert_eq!(escape_wire(r#"with"quote"#), r#"with\"quote"#);
        assert_eq!(escape_wire(r"with\backslash"), r"with\\backslash");
    }

    #[test]
    fn is_python_keyword_hard_keywords() {
        for kw in ["class", "from", "import", "yield", "lambda", "async", "await", "return"] {
            assert!(is_python_keyword(kw), "expected {kw} to be a keyword");
        }
    }

    #[test]
    fn is_python_keyword_soft_keywords() {
        assert!(is_python_keyword("match"));
        assert!(is_python_keyword("case"));
    }

    #[test]
    fn is_python_keyword_normal_names_are_not_keywords() {
        for name in ["id", "tenant", "name", "email", "customer_id", "user_roles"] {
            assert!(!is_python_keyword(name), "expected {name} to NOT be a keyword");
        }
    }

    #[test]
    fn is_python_keyword_is_case_sensitive() {
        // "False", "None", "True" are capitalized keywords in Python; CSL lowercase
        // identifiers cannot collide with them but lowercase variants DO in some
        // Python idioms ("true"/"false" are allowed identifiers). Our lookup treats
        // them case-sensitively.
        assert!(is_python_keyword("False"));
        assert!(is_python_keyword("None"));
        assert!(is_python_keyword("True"));
        assert!(!is_python_keyword("false"));
        assert!(!is_python_keyword("none"));
    }
}

#[cfg(test)]
mod schema_emit_tests {
    use crate::{CompileTargets, compile};

    #[test]
    fn rejects_non_string_tenant_field() {
        let src = r#"
            schema Bad {
                id: Ulid @primary
                tenant: I32
            }
        "#;
        let err = compile(src, CompileTargets::PYTHON).expect_err("should reject");
        let msg = format!("{err}");
        assert!(
            msg.contains("tenant") && (msg.contains("String") || msg.contains("string")),
            "expected error mentioning tenant + String, got: {msg}"
        );
    }

    #[test]
    fn accepts_explicit_string_tenant_field() {
        let src = r#"
            schema Good {
                id: Ulid @primary
                tenant: String
            }
        "#;
        let out = compile(src, CompileTargets::PYTHON).expect("should compile");
        assert!(out.python.contains("tenant: str"));
    }

    #[test]
    fn auto_injects_tenant_when_absent() {
        let src = r#"
            schema Note {
                id: Ulid @primary
                title: String
            }
        "#;
        let out = compile(src, CompileTargets::PYTHON).expect("should compile");
        assert!(out.python.contains("tenant: str"));
    }

    #[test]
    fn optional_field_wraps_in_not_required() {
        let src = r#"
            schema Thing {
                id: Ulid @primary
                score: F32?
            }
        "#;
        let out = compile(src, CompileTargets::PYTHON).expect("should compile");
        assert!(
            out.python.contains("score: NotRequired[float]"),
            "expected NotRequired[float], got:\n{}",
            out.python,
        );
    }

    #[test]
    fn vector_field_is_skipped() {
        let src = r#"
            schema Vec4 {
                id: Ulid @primary
                embedding: Vector<4>
            }
        "#;
        let out = compile(src, CompileTargets::PYTHON).expect("should compile");
        assert!(
            !out.python.contains("embedding"),
            "Vector<N> fields must be skipped, got:\n{}",
            out.python,
        );
    }

    #[test]
    fn optional_vector_field_is_also_skipped() {
        let src = r#"
            schema Vec4 {
                id: Ulid @primary
                embedding: Vector<4>?
            }
        "#;
        let result = compile(src, CompileTargets::PYTHON);
        match result {
            Ok(out) => assert!(
                !out.python.contains("embedding"),
                "Optional<Vector> must also be skipped, got:\n{}",
                out.python,
            ),
            Err(_) => { /* type checker rejected -- also acceptable */ }
        }
    }

    #[test]
    fn i32_i64_both_render_as_int_no_precision_comment() {
        let src = r#"
            schema Counts {
                id: Ulid @primary
                small: I32
                big: I64
            }
        "#;
        let out = compile(src, CompileTargets::PYTHON).expect("should compile");
        assert!(out.python.contains("small: int"));
        assert!(out.python.contains("big: int"));
        // Python ints are arbitrary precision -- no JSDoc-style comment needed.
        assert!(!out.python.contains("2^53"));
    }
}
