//! Rust typed struct codegen.
//!
//! Emits a single `generated.rs` file containing one `pub mod <namespace>` per
//! CSL namespace with struct + enum declarations for each schema. See the
//! design doc §2 for decisions made and rationale.

use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit the full Rust module text for a typed CSL file.
///
/// # Errors
///
/// Propagates any internal contradiction (e.g., a type the emitter does not
/// know how to render) as [`crate::error::CslError::Codegen`].
pub fn emit_rust(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    emit_file_header(&mut out);
    emit_namespace_module(&mut out, typed);
    Ok(out)
}

fn emit_file_header(out: &mut String) {
    out.push_str(
        "//! Generated by `sealstack compile`. Do not edit by hand.\n\
         //!\n\
         //! CSL namespaces with dots are flattened to snake_case modules:\n\
         //! `acme.crm` -> `acme_crm`. This trades nested-module structure for\n\
         //! shorter paths in compile errors consumers will actually read.\n\
         \n\
         #![allow(clippy::pedantic, clippy::nursery)]\n\
         #![allow(dead_code)]\n\
         \n",
    );
}

fn emit_namespace_module(out: &mut String, typed: &TypedFile) {
    let module_name = namespace_module_name(&typed.namespace);
    out.push_str(&format!("pub mod {module_name} {{\n"));
    out.push_str("    use serde::{Deserialize, Serialize};\n\n");
    // Enum and schema emit will be added in subsequent tasks.
    let _ = typed;
    out.push_str("}\n");
}

fn namespace_module_name(namespace: &str) -> String {
    if namespace.is_empty() {
        "default".to_string()
    } else {
        namespace.replace('.', "_")
    }
}
