//! Rust typed struct codegen.
//!
//! Emits a single `generated.rs` file containing one `pub mod <namespace>` per
//! CSL namespace with struct + enum declarations for each schema. See the
//! design doc §2 for decisions made and rationale.

use crate::ast::{PrimitiveType, TypeExpr};
use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit the full Rust module text for a typed CSL file.
///
/// # Errors
///
/// Propagates any internal contradiction (e.g., a type the emitter does not
/// know how to render) as [`crate::error::CslError::Codegen`].
pub fn emit_rust(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    emit_file_header(&mut out);
    emit_namespace_module(&mut out, typed);
    Ok(out)
}

fn emit_file_header(out: &mut String) {
    out.push_str(
        "//! Generated by `sealstack compile`. Do not edit by hand.\n\
         //!\n\
         //! CSL namespaces with dots are flattened to snake_case modules:\n\
         //! `acme.crm` -> `acme_crm`. This trades nested-module structure for\n\
         //! shorter paths in compile errors consumers will actually read.\n\
         \n\
         #![allow(clippy::pedantic, clippy::nursery)]\n\
         #![allow(dead_code)]\n\
         \n",
    );
}

fn emit_namespace_module(out: &mut String, typed: &TypedFile) {
    let module_name = namespace_module_name(&typed.namespace);
    out.push_str(&format!("pub mod {module_name} {{\n"));
    out.push_str("    use serde::{Deserialize, Serialize};\n\n");

    // Enums are not currently tracked in `decl_order` (the type checker only
    // inserts schemas there), so iterate the enums map directly. Sort by name
    // for deterministic output.
    let mut enum_names: Vec<&String> = typed.enums.keys().collect();
    enum_names.sort();
    for name in enum_names {
        if let Some(en) = typed.enums.get(name) {
            emit_enum(out, en);
            out.push('\n');
        }
    }

    for name in &typed.decl_order {
        if let Some(schema) = typed.schemas.get(name) {
            emit_schema_struct(out, &schema.decl);
            out.push('\n');
        }
    }

    out.push_str("}\n");
}

fn emit_enum(out: &mut String, en: &crate::ast::EnumDecl) {
    out.push_str("    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n");
    out.push_str(&format!("    pub enum {} {{\n", en.name));
    for v in &en.variants {
        let wire = v
            .wire
            .clone()
            .unwrap_or_else(|| v.name.to_ascii_lowercase());
        out.push_str(&format!(
            "        #[serde(rename = \"{wire}\")] {ident},\n",
            ident = v.name,
        ));
    }
    out.push_str("    }\n");
}

fn emit_schema_struct(out: &mut String, decl: &crate::ast::SchemaDecl) {
    out.push_str("    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n");
    out.push_str(&format!("    pub struct {} {{\n", decl.name));

    let mut emitted_tenant = false;
    for field in &decl.fields {
        // Vector<N> lives in the vector store, not on the struct. Spec §2.3.
        if matches!(field.ty, crate::ast::TypeExpr::Vector(_, _)) {
            continue;
        }
        if field.name == "tenant" {
            emitted_tenant = true;
        }

        let ty_str = render_field_type(&field.ty);
        let serde_attr = if matches!(field.ty, crate::ast::TypeExpr::Optional(_, _)) {
            "        #[serde(default, skip_serializing_if = \"Option::is_none\")]\n"
        } else {
            ""
        };
        out.push_str(serde_attr);
        out.push_str(&format!("        pub {}: {},\n", field.name, ty_str));
    }

    if !emitted_tenant {
        // Every CSL-generated table carries a tenant column (spec §2.5).
        out.push_str("        pub tenant: String,\n");
    }

    out.push_str("    }\n");
}

fn namespace_module_name(namespace: &str) -> String {
    if namespace.is_empty() {
        "default".to_string()
    } else {
        namespace.replace('.', "_")
    }
}

fn render_field_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Primitive(p, _) => render_primitive(*p).to_string(),
        TypeExpr::Ref(_, _) => "String".to_string(),
        TypeExpr::Named(name, _) => name.clone(),
        TypeExpr::Optional(inner, _) => format!("Option<{}>", render_field_type(inner)),
        TypeExpr::List(inner, _) => format!("Vec<{}>", render_field_type(inner)),
        TypeExpr::Map(k, v, _) => format!(
            "std::collections::HashMap<{}, {}>",
            render_field_type(k),
            render_field_type(v),
        ),
        TypeExpr::Vector(_, _) => "/* vector - skipped */".to_string(),
    }
}

fn render_primitive(p: PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::String | PrimitiveType::Text => "String",
        PrimitiveType::Ulid | PrimitiveType::Uuid => "String",
        PrimitiveType::I32 => "i32",
        PrimitiveType::I64 => "i64",
        PrimitiveType::F32 => "f32",
        PrimitiveType::F64 => "f64",
        PrimitiveType::Bool => "bool",
        PrimitiveType::Instant | PrimitiveType::Duration => "String",
        PrimitiveType::Json => "serde_json::Value",
    }
}

#[cfg(test)]
mod type_mapper_tests {
    use super::*;
    use crate::ast::{PrimitiveType, TypeExpr};
    use crate::span::Span;

    fn s() -> Span {
        Span::point(0)
    }

    #[test]
    fn primitives_map_to_default_types() {
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::String, s())), "String");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::I32, s())), "i32");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Bool, s())), "bool");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Ulid, s())), "String");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Instant, s())), "String");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Json, s())), "serde_json::Value");
    }

    #[test]
    fn optional_wraps_in_option() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::F32, s()));
        assert_eq!(render_field_type(&TypeExpr::Optional(inner, s())), "Option<f32>");
    }

    #[test]
    fn ref_and_named_schema_are_strings() {
        assert_eq!(render_field_type(&TypeExpr::Ref("User".into(), s())), "String");
    }

    #[test]
    fn list_renders_vec() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::String, s()));
        assert_eq!(render_field_type(&TypeExpr::List(inner, s())), "Vec<String>");
    }
}
