//! Rust typed struct codegen.
//!
//! Emits a single `generated.rs` file containing one `pub mod <namespace>` per
//! CSL namespace with struct + enum declarations for each schema. See the
//! design doc §2 for decisions made and rationale.

use super::to_snake;
use crate::ast::{PrimitiveType, TypeExpr};
use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit the full Rust module text for a typed CSL file.
///
/// # Errors
///
/// Propagates any internal contradiction (e.g., a type the emitter does not
/// know how to render) as [`crate::error::CslError::Codegen`].
pub fn emit_rust(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    emit_file_header(&mut out);
    emit_namespace_module(&mut out, typed)?;
    Ok(out)
}

fn emit_file_header(out: &mut String) {
    out.push_str(
        "//! Generated by `sealstack compile`. Do not edit by hand.\n\
         //!\n\
         //! CSL namespaces with dots are flattened to snake_case modules:\n\
         //! `acme.crm` -> `acme_crm`. This trades nested-module structure for\n\
         //! shorter paths in compile errors consumers will actually read.\n\
         \n\
         #![allow(clippy::pedantic, clippy::nursery)]\n\
         #![allow(dead_code)]\n\
         \n",
    );
}

fn emit_namespace_module(out: &mut String, typed: &TypedFile) -> CslResult<()> {
    let module_name = namespace_module_name(&typed.namespace);
    out.push_str(&format!("pub mod {module_name} {{\n"));
    out.push_str("    use serde::{Deserialize, Serialize};\n\n");

    // Enums are not currently tracked in `decl_order` (the type checker only
    // inserts schemas there), so iterate the enums map directly. Sort by name
    // for deterministic output.
    let mut enum_names: Vec<&String> = typed.enums.keys().collect();
    enum_names.sort();
    for name in enum_names {
        if let Some(en) = typed.enums.get(name) {
            emit_enum(out, en);
            out.push('\n');
        }
    }

    for name in &typed.decl_order {
        if let Some(schema) = typed.schemas.get(name) {
            emit_schema_struct(out, &schema.decl, &typed.namespace)?;
            out.push('\n');
        }
    }

    out.push_str("}\n");
    Ok(())
}

fn emit_enum(out: &mut String, en: &crate::ast::EnumDecl) {
    out.push_str("    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n");
    out.push_str(&format!("    pub enum {} {{\n", en.name));
    for v in &en.variants {
        let wire = v
            .wire
            .clone()
            .unwrap_or_else(|| v.name.to_ascii_lowercase());
        // Wire strings flow straight from CSL source into Rust attribute text;
        // escape backslashes and quotes so a variant like `Q("val\"ue")` still
        // produces valid Rust.
        let wire_escaped = wire.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!(
            "        #[serde(rename = \"{wire_escaped}\")] {ident},\n",
            ident = v.name,
        ));
    }
    out.push_str("    }\n");
}

fn emit_schema_struct(
    out: &mut String,
    decl: &crate::ast::SchemaDecl,
    namespace: &str,
) -> CslResult<()> {
    out.push_str("    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n");
    out.push_str(&format!("    pub struct {} {{\n", decl.name));

    let mut emitted_tenant = false;
    for field in &decl.fields {
        // Vector<N> lives in the vector store, not on the struct. Spec §2.3.
        if matches!(field.ty, crate::ast::TypeExpr::Vector(_, _)) {
            continue;
        }
        // Guard: the SQL emitter always writes `tenant text NOT NULL`, so a
        // user-declared `tenant` field must be String/Text. Otherwise serde
        // deserialisation of `""` into e.g. `i32` fails at runtime with a
        // cryptic "invalid type" error far from the declaration site.
        if field.name == "tenant"
            && !matches!(
                field.ty,
                crate::ast::TypeExpr::Primitive(
                    crate::ast::PrimitiveType::String | crate::ast::PrimitiveType::Text,
                    _,
                ),
            )
        {
            return Err(crate::error::CslError::Codegen {
                message: format!(
                    "schema `{}` declares `tenant` field with non-String type; the tenant column is always `text` in SQL and the Rust struct must match",
                    decl.name,
                ),
            });
        }
        if field.name == "tenant" {
            emitted_tenant = true;
        }

        let ty_str = render_field_type(&field.ty);
        let serde_attr = if matches!(field.ty, crate::ast::TypeExpr::Optional(_, _)) {
            "        #[serde(default, skip_serializing_if = \"Option::is_none\")]\n"
        } else {
            ""
        };
        out.push_str(serde_attr);
        out.push_str(&format!("        pub {}: {},\n", field.name, ty_str));
    }

    if !emitted_tenant {
        // Every CSL-generated table carries a tenant column (spec §2.5).
        out.push_str("        pub tenant: String,\n");
    }

    out.push_str("    }\n\n");

    emit_schema_impl(out, decl, namespace);
    Ok(())
}

fn emit_schema_impl(out: &mut String, decl: &crate::ast::SchemaDecl, namespace: &str) {
    let primary_key = decl
        .fields
        .iter()
        .find(|f| f.decorators.iter().any(|d| d.is("primary")))
        .map(|f| f.name.clone())
        .unwrap_or_else(|| "id".to_string());

    let version = decl.version.unwrap_or(1);
    let table = to_snake(&decl.name);
    let namespace_literal = if namespace.is_empty() {
        "default"
    } else {
        namespace
    };

    out.push_str(&format!("    impl {} {{\n", decl.name));
    out.push_str(&format!(
        "        pub const NAMESPACE:   &'static str = \"{namespace_literal}\";\n"
    ));
    out.push_str(&format!(
        "        pub const SCHEMA:      &'static str = \"{}\";\n",
        decl.name
    ));
    out.push_str(&format!(
        "        pub const TABLE:       &'static str = \"{table}\";\n"
    ));
    out.push_str(&format!(
        "        pub const VERSION:     u32          = {version};\n"
    ));
    out.push_str(&format!(
        "        pub const PRIMARY_KEY: &'static str = \"{primary_key}\";\n"
    ));

    for rel in &decl.relations {
        let const_name = format!("RELATION_{}", rel.name.to_ascii_uppercase());
        let fk = rel.via.segments.last().cloned().unwrap_or_default();
        let target = &rel.target;
        out.push_str(&format!(
            "        pub const {const_name}: (&'static str, &'static str) = (\"{target}\", \"{fk}\");\n"
        ));
    }

    out.push_str("    }\n");
}

fn namespace_module_name(namespace: &str) -> String {
    if namespace.is_empty() {
        "default".to_string()
    } else {
        namespace.replace('.', "_")
    }
}

fn render_field_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Primitive(p, _) => render_primitive(*p).to_string(),
        TypeExpr::Ref(_, _) => "String".to_string(),
        TypeExpr::Named(name, _) => name.clone(),
        TypeExpr::Optional(inner, _) => format!("Option<{}>", render_field_type(inner)),
        TypeExpr::List(inner, _) => format!("Vec<{}>", render_field_type(inner)),
        TypeExpr::Map(k, v, _) => format!(
            "std::collections::HashMap<{}, {}>",
            render_field_type(k),
            render_field_type(v),
        ),
        TypeExpr::Vector(_, _) => "/* vector - skipped */".to_string(),
    }
}

fn render_primitive(p: PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::String | PrimitiveType::Text => "String",
        PrimitiveType::Ulid | PrimitiveType::Uuid => "String",
        PrimitiveType::I32 => "i32",
        PrimitiveType::I64 => "i64",
        PrimitiveType::F32 => "f32",
        PrimitiveType::F64 => "f64",
        PrimitiveType::Bool => "bool",
        PrimitiveType::Instant | PrimitiveType::Duration => "String",
        PrimitiveType::Json => "serde_json::Value",
    }
}

#[cfg(test)]
mod type_mapper_tests {
    use super::*;
    use crate::ast::{PrimitiveType, TypeExpr};
    use crate::span::Span;

    fn s() -> Span {
        Span::point(0)
    }

    #[test]
    fn primitives_map_to_default_types() {
        assert_eq!(
            render_field_type(&TypeExpr::Primitive(PrimitiveType::String, s())),
            "String"
        );
        assert_eq!(
            render_field_type(&TypeExpr::Primitive(PrimitiveType::I32, s())),
            "i32"
        );
        assert_eq!(
            render_field_type(&TypeExpr::Primitive(PrimitiveType::Bool, s())),
            "bool"
        );
        assert_eq!(
            render_field_type(&TypeExpr::Primitive(PrimitiveType::Ulid, s())),
            "String"
        );
        assert_eq!(
            render_field_type(&TypeExpr::Primitive(PrimitiveType::Instant, s())),
            "String"
        );
        assert_eq!(
            render_field_type(&TypeExpr::Primitive(PrimitiveType::Json, s())),
            "serde_json::Value"
        );
    }

    #[test]
    fn optional_wraps_in_option() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::F32, s()));
        assert_eq!(
            render_field_type(&TypeExpr::Optional(inner, s())),
            "Option<f32>"
        );
    }

    #[test]
    fn ref_and_named_schema_are_strings() {
        assert_eq!(
            render_field_type(&TypeExpr::Ref("User".into(), s())),
            "String"
        );
    }

    #[test]
    fn list_renders_vec() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::String, s()));
        assert_eq!(
            render_field_type(&TypeExpr::List(inner, s())),
            "Vec<String>"
        );
    }
}

#[cfg(test)]
mod tenant_guard_tests {
    use crate::{CompileTargets, compile};

    #[test]
    fn rejects_non_string_tenant_field() {
        let src = r#"
            schema Bad {
                id: Ulid @primary
                tenant: I32
            }
        "#;
        let err = compile(src, CompileTargets::RUST).expect_err("should reject");
        let msg = format!("{err}");
        assert!(
            msg.contains("tenant") && msg.contains("String"),
            "expected error mentioning tenant + String, got: {msg}"
        );
    }

    #[test]
    fn accepts_string_tenant_field() {
        let src = r#"
            schema Good {
                id: Ulid @primary
                tenant: String
            }
        "#;
        let out = compile(src, CompileTargets::RUST).expect("should compile");
        assert!(out.rust.contains("pub tenant: String"));
    }

    #[test]
    fn escapes_quotes_in_enum_wire_form() {
        // Wire strings can't contain raw `"` via the CSL lexer's current
        // string rules, so drive the emitter directly with a constructed AST.
        use crate::ast::{EnumDecl, EnumVariant};
        use crate::span::Span;

        let en = EnumDecl {
            name: "Weird".into(),
            variants: vec![EnumVariant {
                name: "Q".into(),
                wire: Some(r#"val"ue"#.into()),
                span: Span::point(0),
            }],
            span: Span::point(0),
        };

        let mut out = String::new();
        super::emit_enum(&mut out, &en);
        assert!(out.contains(r#"rename = "val\"ue""#), "got: {out}");
    }
}
