//! Postgres-dialect SQL code generation.
//!
//! For each schema, we emit a `CREATE TABLE` with columns mapped from CSL
//! primitives, plus a fixed set of convention columns
//! (`body`, `created_at`, `tenant`, `metadata`) that the engine's row writer
//! at `crates/sealstack-engine/src/ingest.rs` references by name. `@chunked`
//! fields stay on the parent row as plain `text` for BM25; chunk-and-embed
//! happens at ingest time and writes to the vector store, not to a sidecar
//! SQL table. Indexes for `@indexed`/`@unique`/`@searchable` fields and
//! foreign-key constraints for `Ref<T>` fields are emitted too.
//!
//! This module emits forward migrations only. Downgrade migrations are produced
//! by a sibling function that diffs two schema versions — not shown here.

use crate::ast::{FieldDecl, PrimitiveType, SchemaDecl, TypeExpr};
use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit a single SQL string containing all schemas' DDL, in declaration order.
///
/// # Errors
/// Returns a [`CslError::Codegen`] if an unsupported type appears.
pub fn emit_sql(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    out.push_str("-- Generated by sealstack-csl. Do not edit manually.\n");
    if !typed.namespace.is_empty() {
        out.push_str(&format!("-- namespace: {}\n", typed.namespace));
    }
    out.push_str("SET statement_timeout = '60s';\n\n");

    for name in &typed.decl_order {
        let Some(schema) = typed.schemas.get(name) else {
            continue;
        };
        emit_schema(&schema.decl, &mut out)?;
        out.push('\n');
    }
    Ok(out)
}

fn emit_schema(schema: &SchemaDecl, out: &mut String) -> CslResult<()> {
    let table = table_name(&schema.name);
    out.push_str(&format!("CREATE TABLE IF NOT EXISTS {table} (\n"));

    // Emit one column per declared field. `@chunked` fields stay on the parent
    // table as plain `text`; they're separately chunked + embedded into the
    // vector store at ingest time. The earlier `*_chunk` sidecar table design
    // wasn't actually written to by the engine (which keeps full body on the
    // parent row and offloads chunks to the vector store), so omitting it
    // here closes a schema/codegen drift that breaks every ingest.
    let mut column_lines: Vec<String> = Vec::new();
    for f in &schema.fields {
        let sql_type = map_type(&f.ty);
        let nullable = if f.ty.is_optional() { "" } else { " NOT NULL" };
        let mut line = format!(
            "  {name} {ty}{null}",
            name = f.name,
            ty = sql_type,
            null = nullable
        );

        if f.decorators.iter().any(|d| d.is("primary")) {
            line.push_str(" PRIMARY KEY");
        }
        if f.decorators.iter().any(|d| d.is("unique"))
            && !f.decorators.iter().any(|d| d.is("primary"))
        {
            line.push_str(" UNIQUE");
        }
        column_lines.push(line);
    }

    // Convention columns added to every CSL-generated table. They match the
    // engine's `INSERT INTO ... (id, title, body, created_at, tenant, metadata)`
    // shape (see `crates/sealstack-engine/src/ingest.rs`):
    //   - `body`        — concatenated chunked-field text for BM25 search
    //                     against `to_tsvector('english', body)`
    //   - `created_at`  — record-level timestamp populated from the connector's
    //                     `source_updated_at`
    //   - `tenant`      — multi-tenant isolation key, empty string means
    //                     "default tenant"
    //   - `metadata`    — JSONB sidecar carrying connector-specific extras
    // Each is only emitted when the schema doesn't already declare a field of
    // the same name, so user schemas keep authority over their own typing.
    if !schema.fields.iter().any(|f| f.name == "body") && !schema.fields.iter().any(is_chunked) {
        column_lines.push("  body text NOT NULL DEFAULT ''".to_string());
    }
    if !schema.fields.iter().any(|f| f.name == "created_at") {
        column_lines.push("  created_at timestamptz NOT NULL DEFAULT now()".to_string());
    }
    if !schema.fields.iter().any(|f| f.name == "tenant") {
        column_lines.push("  tenant text NOT NULL DEFAULT ''".to_string());
    }
    if !schema.fields.iter().any(|f| f.name == "metadata") {
        column_lines.push("  metadata jsonb NOT NULL DEFAULT '{}'::jsonb".to_string());
    }

    // Emit foreign keys for Ref<T> fields.
    for f in &schema.fields {
        if let TypeExpr::Ref(target, _) = &f.ty {
            let line = format!(
                "  FOREIGN KEY ({name}) REFERENCES {target_table} (id)",
                name = f.name,
                target_table = table_name(target),
            );
            column_lines.push(line);
        }
    }

    out.push_str(&column_lines.join(",\n"));
    out.push_str("\n);\n");

    // Tenant scoping index (matches the retrieval layer's `coalesce(tenant,'') = $N`).
    out.push_str(&format!(
        "CREATE INDEX IF NOT EXISTS {table}_tenant_idx ON {table} (tenant);\n",
    ));

    // Indexes.
    for f in &schema.fields {
        if f.decorators.iter().any(|d| d.is("indexed")) {
            let col = &f.name;
            out.push_str(&format!(
                "CREATE INDEX IF NOT EXISTS {table}_{col}_idx ON {table} ({col});\n",
            ));
        }
        if f.decorators.iter().any(|d| d.is("searchable")) {
            let col = &f.name;
            out.push_str(&format!(
                "CREATE INDEX IF NOT EXISTS {table}_{col}_fts_idx ON {table} USING gin (to_tsvector('english', {col}));\n",
            ));
        }
    }

    // BM25 retrieval reads `to_tsvector('english', body)`. Index it so the
    // search is sub-millisecond instead of a sequential scan on every query.
    // `CREATE INDEX IF NOT EXISTS` is a no-op if the schema explicitly
    // declared `body` with `@searchable` (the per-field branch above already
    // produced the same name `{table}_body_fts_idx`).
    out.push_str(&format!(
        "CREATE INDEX IF NOT EXISTS {table}_body_fts_idx ON {table} USING gin (to_tsvector('english', body));\n",
    ));

    Ok(())
}

fn is_chunked(f: &FieldDecl) -> bool {
    f.decorators.iter().any(|d| d.is("chunked"))
}

fn table_name(schema_name: &str) -> String {
    // lower_snake_case
    let mut out = String::with_capacity(schema_name.len() + 2);
    for (i, c) in schema_name.chars().enumerate() {
        if c.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

fn map_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Optional(inner, _) => map_type(inner),
        TypeExpr::Primitive(p, _) => map_primitive(*p).to_owned(),
        TypeExpr::Ref(_, _) => "text".to_owned(), // FK column type mirrors Ulid representation
        TypeExpr::Vector(_, _) => "bytea".to_owned(), // vectors live in the vector store, placeholder
        TypeExpr::List(_, _) => "jsonb".to_owned(),
        TypeExpr::Map(_, _, _) => "jsonb".to_owned(),
        TypeExpr::Named(_, _) => "text".to_owned(), // enums rendered as text for now
    }
}

fn map_primitive(p: PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::String | PrimitiveType::Text => "text",
        // ULIDs are bound as 26-char Crockford-base32 strings by the engine's
        // ingest layer (`record_id = Ulid::new().to_string()`), so the column
        // is `text` rather than `bytea`. Switching to `bytea` would require
        // changing every sqlx bind site; `text` round-trips cleanly through
        // sqlx, makes ad-hoc psql inspection readable, and preserves lexical
        // sort order since ULID Crockford-base32 is monotonic over time.
        PrimitiveType::Ulid => "text",
        PrimitiveType::Uuid => "uuid",
        PrimitiveType::I32 => "integer",
        PrimitiveType::I64 => "bigint",
        PrimitiveType::F32 => "real",
        PrimitiveType::F64 => "double precision",
        PrimitiveType::Bool => "boolean",
        PrimitiveType::Instant => "timestamptz",
        PrimitiveType::Duration => "interval",
        PrimitiveType::Json => "jsonb",
    }
}

#[cfg(test)]
mod tests {
    use crate::parser::parse_file;
    use crate::types::check;

    /// Compile a CSL snippet and emit its SQL. Panics on parse / typecheck error
    /// (tests want a single-line surface; failures here mean the fixture is bad).
    fn sql_of(src: &str) -> String {
        let parsed = parse_file(src).expect("parse");
        let typed = check(&parsed).expect("typecheck");
        super::emit_sql(&typed).expect("emit_sql")
    }

    /// Every CSL-generated table MUST carry these columns; the engine's
    /// `INSERT INTO ... (id, title, body, created_at, tenant, metadata)` bind
    /// site at `crates/sealstack-engine/src/ingest.rs` references them by name.
    /// Drift between the SQL emitter and the engine row writer is the entire
    /// reason `admin_only_policy_filters_non_admin_results` was broken.
    #[test]
    fn parent_table_carries_engine_convention_columns() {
        let sql = sql_of(
            r#"namespace examples
schema Doc {
    id:    Ulid   @primary
    title: String @searchable
    body:  Text   @chunked
}
"#,
        );

        for col in [
            "id text",    // ULID is bound as a string, not bytea
            "title text", // declared schema field
            "body text",  // @chunked field stays on parent for BM25 + INSERT
            "created_at timestamptz",
            "tenant text",
            "metadata jsonb",
        ] {
            assert!(
                sql.contains(col),
                "expected `{col}` in generated DDL but it was missing:\n{sql}",
            );
        }
        // The body FTS index has to exist for BM25 search to be sub-millisecond.
        assert!(
            sql.contains("USING gin (to_tsvector('english', body))"),
            "expected GIN FTS index on body column:\n{sql}",
        );
    }

    /// If the user declares their own `body` field, the emitter must not
    /// duplicate it as a convention column.
    #[test]
    fn convention_columns_yield_to_user_declared_fields() {
        let sql = sql_of(
            r#"namespace examples
schema Doc {
    id:       Ulid   @primary
    body:     Text   @chunked
    tenant:   String
    metadata: Json
}
"#,
        );
        // Each name should appear in exactly one column-line context — the user's.
        let count = |needle: &str| sql.matches(needle).count();
        assert_eq!(count("tenant text"), 1, "tenant duplicated:\n{sql}");
        assert!(
            !sql.contains("tenant text NOT NULL DEFAULT ''"),
            "user-declared tenant must not get the convention default:\n{sql}",
        );
        assert!(
            !sql.contains("metadata jsonb NOT NULL DEFAULT '{}'::jsonb"),
            "user-declared metadata must not get the convention default:\n{sql}",
        );
    }

    /// Ref<T> foreign keys must point at a `text` `id` column (matching the
    /// ULID-as-text convention).
    #[test]
    fn ref_columns_match_id_column_type() {
        let sql = sql_of(
            r#"namespace examples
schema Doc {
    id:    Ulid   @primary
    title: String
}

schema Comment {
    id:   Ulid     @primary
    doc:  Ref<Doc>
    body: Text     @chunked
}
"#,
        );
        assert!(
            sql.contains("doc text"),
            "Ref column should be text, not bytea:\n{sql}",
        );
        assert!(
            sql.contains("FOREIGN KEY (doc) REFERENCES doc (id)"),
            "FK clause should still be emitted:\n{sql}",
        );
    }
}
