//! TypeScript record-type codegen.
//!
//! Emits a single `generated.ts` file containing one `export interface <Schema>`
//! + one `export const <Schema>Meta` + one `export type <Enum>` per declaration.
//! See `docs/superpowers/specs/2026-04-21-csl-codegen-typescript-design.md`
//! for the shape decisions.

use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit the full TypeScript module text for a typed CSL file.
///
/// # Errors
///
/// Returns [`crate::error::CslError::Codegen`] for an unsupported AST shape
/// (e.g., `Map<K, V>` fields, or a `tenant` field with a non-String type).
pub fn emit_typescript(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    emit_file_header(&mut out);
    // Enum and schema emission land in tasks T2 and T3.
    let _ = typed;
    Ok(out)
}

fn emit_file_header(out: &mut String) {
    out.push_str(
        "// Generated by `sealstack compile`. Do not edit.\n\
         /* eslint-disable */\n\
         /* tslint:disable */\n\
         \n",
    );
}
