//! TypeScript record-type codegen.
//!
//! Emits a single `generated.ts` file containing one `export interface <Schema>`
//! + one `export const <Schema>Meta` + one `export type <Enum>` per declaration.
//! See `docs/superpowers/specs/2026-04-21-csl-codegen-typescript-design.md`
//! for the shape decisions.

use crate::error::CslResult;
use crate::types::TypedFile;

/// Emit the full TypeScript module text for a typed CSL file.
///
/// # Errors
///
/// Returns [`crate::error::CslError::Codegen`] for an unsupported AST shape
/// (e.g., `Map<K, V>` fields, or a `tenant` field with a non-String type).
pub fn emit_typescript(typed: &TypedFile) -> CslResult<String> {
    let mut out = String::new();
    emit_file_header(&mut out);
    // Enums first (sorted by key for deterministic output), then schemas
    // (source order from the CSL file). Schema emission lands in Task T4.
    let mut enum_names: Vec<&String> = typed.enums.keys().collect();
    enum_names.sort();
    for name in enum_names {
        if let Some(en) = typed.enums.get(name) {
            emit_enum(&mut out, en);
        }
    }
    if !typed.enums.is_empty() {
        out.push('\n');
    }
    for name in &typed.decl_order {
        if let Some(schema) = typed.schemas.get(name) {
            emit_schema(&mut out, &schema.decl)?;
            out.push('\n');
            emit_schema_meta(&mut out, &schema.decl, &typed.namespace);
            out.push('\n');
        }
    }
    Ok(out)
}

fn emit_file_header(out: &mut String) {
    out.push_str(
        "// Generated by `sealstack compile`. Do not edit.\n\
         /* eslint-disable */\n\
         /* tslint:disable */\n\
         \n",
    );
}

use crate::ast::{PrimitiveType, TypeExpr};
use crate::error::CslError;

fn render_field_type(ty: &TypeExpr) -> CslResult<String> {
    match ty {
        TypeExpr::Primitive(p, _) => Ok(render_primitive(*p).to_string()),
        TypeExpr::Ref(_, _) => Ok("string".to_string()),
        TypeExpr::Named(name, _) => Ok(name.clone()),
        TypeExpr::Optional(inner, _) => render_field_type(inner),
        TypeExpr::List(inner, _) => Ok(format!("{}[]", render_field_type(inner)?)),
        TypeExpr::Vector(_, _) => Err(CslError::Codegen {
            message: "Vector<N> reached render_field_type; callers must filter vector fields before rendering them (see emit_schema's is_vector guard)".into(),
        }),
        TypeExpr::Map(_, _, _) => Err(CslError::Codegen {
            message: "Map<K, V> fields are not supported in TypeScript codegen (type checker should have rejected this)".into(),
        }),
    }
}

fn render_primitive(p: PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::String | PrimitiveType::Text => "string",
        PrimitiveType::Ulid | PrimitiveType::Uuid => "string",
        PrimitiveType::I32 | PrimitiveType::I64 | PrimitiveType::F32 | PrimitiveType::F64 => "number",
        PrimitiveType::Bool => "boolean",
        PrimitiveType::Instant | PrimitiveType::Duration => "string",
        PrimitiveType::Json => "unknown",
    }
}

/// Whether the given type expression is (or wraps) an `I64`. Used to emit the
/// JSDoc precision warning on I64 fields.
fn is_i64(ty: &TypeExpr) -> bool {
    match ty {
        TypeExpr::Primitive(PrimitiveType::I64, _) => true,
        TypeExpr::Optional(inner, _) => is_i64(inner),
        _ => false,
    }
}

fn emit_enum(out: &mut String, en: &crate::ast::EnumDecl) {
    out.push_str(&format!("export type {} = ", en.name));
    let mut first = true;
    for v in &en.variants {
        if !first {
            out.push_str(" | ");
        }
        first = false;
        let wire = v
            .wire
            .clone()
            .unwrap_or_else(|| v.name.to_ascii_lowercase());
        out.push('\'');
        out.push_str(&escape_wire(&wire));
        out.push('\'');
    }
    out.push_str(";\n");
}

fn escape_wire(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

fn emit_schema_meta(out: &mut String, decl: &crate::ast::SchemaDecl, namespace: &str) {
    let primary_key = decl
        .fields
        .iter()
        .find(|f| f.decorators.iter().any(|d| d.is("primary")))
        .map(|f| f.name.clone())
        .unwrap_or_else(|| "id".to_string());

    let version = decl.version.unwrap_or(1);
    let table = super::to_snake(&decl.name);
    let ns_literal = if namespace.is_empty() { "default" } else { namespace };

    out.push_str(&format!("export const {}Meta = {{\n", decl.name));
    out.push_str(&format!("  NAMESPACE: '{}',\n", escape_wire(ns_literal)));
    out.push_str(&format!("  SCHEMA: '{}',\n", escape_wire(&decl.name)));
    out.push_str(&format!("  TABLE: '{}',\n", escape_wire(&table)));
    out.push_str(&format!("  VERSION: {version},\n"));
    out.push_str(&format!("  PRIMARY_KEY: '{}',\n", escape_wire(&primary_key)));

    out.push_str("  RELATIONS: {");
    if decl.relations.is_empty() {
        out.push_str("},\n");
    } else {
        out.push('\n');
        for rel in &decl.relations {
            let fk = rel.via.segments.last().cloned().unwrap_or_default();
            let target = &rel.target;
            // `rel.name` is a CSL identifier — lexer enforces `[a-z_][a-z0-9_]*`
            // (see parser.rs::ident), which is a strict subset of valid JS
            // identifier characters, so it emits safely as a bare object key.
            // `target` and `fk` live inside string literals and still need escape_wire.
            out.push_str(&format!(
                "    {name}: {{ target: '{target}', fk: '{fk}' }},\n",
                name = rel.name,
                target = escape_wire(target),
                fk = escape_wire(&fk),
            ));
        }
        out.push_str("  },\n");
    }

    out.push_str("} as const;\n");
}

fn emit_schema(out: &mut String, decl: &crate::ast::SchemaDecl) -> CslResult<()> {
    out.push_str(&format!("export interface {} {{\n", decl.name));

    // Vector fields live in the vector store, not on the record (§3.3). Skip
    // both bare `Vector<N>` and `Optional<Vector<N>>` — the wrapper does not
    // change where the data lives, and the parser accepts `Vector<N>?` today
    // (parser.rs::type_expr attaches `?` after any non-optional type, and the
    // type checker does not reject the combination).
    let is_vector = |ty: &crate::ast::TypeExpr| -> bool {
        match ty {
            crate::ast::TypeExpr::Vector(_, _) => true,
            crate::ast::TypeExpr::Optional(inner, _) => {
                matches!(inner.as_ref(), crate::ast::TypeExpr::Vector(_, _))
            }
            _ => false,
        }
    };

    let mut emitted_tenant = false;
    for field in &decl.fields {
        if is_vector(&field.ty) {
            continue;
        }

        if field.name == "tenant" {
            let is_string_or_text = matches!(
                &field.ty,
                crate::ast::TypeExpr::Primitive(
                    crate::ast::PrimitiveType::String | crate::ast::PrimitiveType::Text,
                    _,
                ),
            );
            if !is_string_or_text {
                return Err(CslError::Codegen {
                    message: format!(
                        "schema `{}` declares `tenant` field with non-String type; the tenant column is always `text` in SQL and the TypeScript interface must match (see spec §6)",
                        decl.name,
                    ),
                });
            }
            emitted_tenant = true;
        }

        if is_i64(&field.ty) {
            out.push_str("  /** CSL I64; values above 2^53 lose precision. */\n");
        }

        let ty_str = render_field_type(&field.ty)?;
        let optional = matches!(field.ty, crate::ast::TypeExpr::Optional(_, _));
        let mark = if optional { "?" } else { "" };
        out.push_str(&format!("  {name}{mark}: {ty};\n", name = field.name, ty = ty_str));
    }

    if !emitted_tenant {
        out.push_str("  tenant: string;\n");
    }

    out.push_str("}\n");
    Ok(())
}

#[cfg(test)]
mod type_mapper_tests {
    use super::*;
    use crate::ast::{PrimitiveType, TypeExpr};
    use crate::span::Span;

    fn s() -> Span {
        Span::point(0)
    }

    #[test]
    fn primitives_map_to_default_types() {
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::String, s())).unwrap(), "string");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Text, s())).unwrap(), "string");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Ulid, s())).unwrap(), "string");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Uuid, s())).unwrap(), "string");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::I32, s())).unwrap(), "number");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::I64, s())).unwrap(), "number");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::F32, s())).unwrap(), "number");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::F64, s())).unwrap(), "number");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Bool, s())).unwrap(), "boolean");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Instant, s())).unwrap(), "string");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Duration, s())).unwrap(), "string");
        assert_eq!(render_field_type(&TypeExpr::Primitive(PrimitiveType::Json, s())).unwrap(), "unknown");
    }

    #[test]
    fn ref_and_named_schema_render_as_string() {
        assert_eq!(render_field_type(&TypeExpr::Ref("User".into(), s())).unwrap(), "string");
    }

    #[test]
    fn list_renders_array_suffix() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::String, s()));
        assert_eq!(render_field_type(&TypeExpr::List(inner, s())).unwrap(), "string[]");
    }

    #[test]
    fn nested_list_renders_nested_array() {
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::I32, s()));
        let outer = Box::new(TypeExpr::List(inner, s()));
        assert_eq!(render_field_type(&TypeExpr::List(outer, s())).unwrap(), "number[][]");
    }

    #[test]
    fn optional_is_transparent_to_type_renderer() {
        // render_field_type does NOT prepend `| undefined` — the ?: syntax
        // on the field handles optionality at the field level. This test
        // asserts the renderer returns the inner type unchanged.
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::F32, s()));
        assert_eq!(render_field_type(&TypeExpr::Optional(inner, s())).unwrap(), "number");
    }

    #[test]
    fn map_returns_codegen_error() {
        let k = Box::new(TypeExpr::Primitive(PrimitiveType::String, s()));
        let v = Box::new(TypeExpr::Primitive(PrimitiveType::I32, s()));
        assert!(matches!(
            render_field_type(&TypeExpr::Map(k, v, s())),
            Err(crate::error::CslError::Codegen { .. })
        ));
    }

    #[test]
    fn is_i64_sees_through_optional() {
        assert!(is_i64(&TypeExpr::Primitive(PrimitiveType::I64, s())));
        let inner = Box::new(TypeExpr::Primitive(PrimitiveType::I64, s()));
        assert!(is_i64(&TypeExpr::Optional(inner, s())));
        assert!(!is_i64(&TypeExpr::Primitive(PrimitiveType::I32, s())));
    }
}

#[cfg(test)]
mod enum_emit_tests {
    use super::*;
    use crate::ast::{EnumDecl, EnumVariant};
    use crate::span::Span;

    fn s() -> Span {
        Span::point(0)
    }

    #[test]
    fn emit_enum_with_explicit_wire_forms() {
        let en = EnumDecl {
            name: "Tier".into(),
            variants: vec![
                EnumVariant { name: "Free".into(), wire: Some("free".into()), span: s() },
                EnumVariant { name: "Pro".into(), wire: Some("pro".into()), span: s() },
                EnumVariant { name: "Enterprise".into(), wire: Some("enterprise".into()), span: s() },
            ],
            span: s(),
        };
        let mut out = String::new();
        emit_enum(&mut out, &en);
        assert_eq!(
            out,
            "export type Tier = 'free' | 'pro' | 'enterprise';\n"
        );
    }

    #[test]
    fn emit_enum_falls_back_to_lowercased_ident() {
        let en = EnumDecl {
            name: "Status".into(),
            variants: vec![
                EnumVariant { name: "Active".into(), wire: None, span: s() },
                EnumVariant { name: "Archived".into(), wire: None, span: s() },
            ],
            span: s(),
        };
        let mut out = String::new();
        emit_enum(&mut out, &en);
        assert_eq!(out, "export type Status = 'active' | 'archived';\n");
    }

    #[test]
    fn escapes_backslash_and_single_quote_in_wire_form() {
        let en = EnumDecl {
            name: "Weird".into(),
            variants: vec![
                EnumVariant { name: "Q".into(), wire: Some(r#"val'ue\n"#.into()), span: s() },
            ],
            span: s(),
        };
        let mut out = String::new();
        emit_enum(&mut out, &en);
        // The wire string contains a literal `'` and a literal `\` followed by `n`.
        // Both must be escaped: `'` → `\'`, `\` → `\\`.
        assert_eq!(out, r"export type Weird = 'val\'ue\\n';" .to_string() + "\n");
    }
}

#[cfg(test)]
mod schema_emit_tests {
    use crate::{CompileTargets, compile};

    #[test]
    fn rejects_non_string_tenant_field() {
        let src = r#"
            schema Bad {
                id: Ulid @primary
                tenant: I32
            }
        "#;
        let err = compile(src, CompileTargets::TYPESCRIPT).expect_err("should reject");
        let msg = format!("{err}");
        assert!(
            msg.contains("tenant") && (msg.contains("String") || msg.contains("string")),
            "expected error mentioning tenant + String, got: {msg}"
        );
    }

    #[test]
    fn accepts_explicit_string_tenant_field() {
        let src = r#"
            schema Good {
                id: Ulid @primary
                tenant: String
            }
        "#;
        let out = compile(src, CompileTargets::TYPESCRIPT).expect("should compile");
        assert!(out.typescript.contains("tenant: string;"));
    }

    #[test]
    fn auto_injects_tenant_when_absent() {
        let src = r#"
            schema Note {
                id: Ulid @primary
                title: String
            }
        "#;
        let out = compile(src, CompileTargets::TYPESCRIPT).expect("should compile");
        assert!(out.typescript.contains("tenant: string;"));
    }

    #[test]
    fn optional_field_uses_question_mark_syntax() {
        let src = r#"
            schema Thing {
                id: Ulid @primary
                score: F32?
            }
        "#;
        let out = compile(src, CompileTargets::TYPESCRIPT).expect("should compile");
        assert!(
            out.typescript.contains("score?: number;"),
            "expected optional `?:` syntax, got:\n{}",
            out.typescript
        );
    }

    #[test]
    fn vector_field_is_skipped() {
        let src = r#"
            schema Vec4 {
                id: Ulid @primary
                embedding: Vector<4>
            }
        "#;
        let out = compile(src, CompileTargets::TYPESCRIPT).expect("should compile");
        assert!(
            !out.typescript.contains("embedding"),
            "Vector<N> fields must be skipped, got:\n{}",
            out.typescript
        );
    }

    #[test]
    fn optional_vector_field_is_handled() {
        let src = r#"
            schema Vec4 {
                id: Ulid @primary
                embedding: Vector<4>?
            }
        "#;
        // Either the type checker rejects this (acceptable), or the emitter
        // skips the field like a bare Vector (preferred). Both behaviours
        // keep the generated TypeScript valid.
        let result = compile(src, CompileTargets::TYPESCRIPT);
        match result {
            Ok(out) => assert!(
                !out.typescript.contains("embedding"),
                "optional Vector should be skipped like bare Vector; got:\n{}",
                out.typescript
            ),
            Err(_) => { /* type checker rejected — also acceptable */ }
        }
    }

    #[test]
    fn i64_field_emits_jsdoc_precision_warning() {
        let src = r#"
            schema Big {
                id: Ulid @primary
                counter: I64
            }
        "#;
        let out = compile(src, CompileTargets::TYPESCRIPT).expect("should compile");
        assert!(
            out.typescript.contains("2^53"),
            "expected I64 JSDoc precision warning, got:\n{}",
            out.typescript
        );
    }

    #[test]
    fn meta_const_includes_all_reflection_fields() {
        let src = r#"
            namespace acme.crm

            schema Customer version 2 {
                id:    Ulid @primary
                owner: Ref<User>

                relations {
                    tickets: many Ticket via Ticket.customer on_delete cascade
                }
            }

            schema User {
                id: Ulid @primary
            }

            schema Ticket {
                id:       Ulid @primary
                customer: Ref<Customer>
            }
        "#;
        let out = compile(src, CompileTargets::TYPESCRIPT).expect("compile");
        // Check the presence of every meta field on Customer.
        for needle in [
            "export const CustomerMeta = {",
            "NAMESPACE: 'acme.crm',",
            "SCHEMA: 'Customer',",
            "TABLE: 'customer',",
            "VERSION: 2,",
            "PRIMARY_KEY: 'id',",
            "RELATIONS: {",
            "tickets: { target: 'Ticket', fk: 'customer' },",
            "} as const;",
        ] {
            assert!(
                out.typescript.contains(needle),
                "expected `{}` in output, got:\n{}",
                needle,
                out.typescript,
            );
        }
    }

    #[test]
    fn meta_const_emits_empty_relations_when_none() {
        let src = r#"
            schema Simple {
                id: Ulid @primary
            }
        "#;
        let out = compile(src, CompileTargets::TYPESCRIPT).expect("compile");
        assert!(
            out.typescript.contains("RELATIONS: {},"),
            "expected RELATIONS: {{}} for relation-less schema, got:\n{}",
            out.typescript
        );
    }
}
