# generated by datamodel-codegen:
#   filename:  ApplyDdlResponse.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ApplyDdlResponse(BaseModel):
    """
    Response data for `POST /v1/schemas/{qualified}/ddl`.
    """

    applied: Annotated[int, Field(description='Number of statements applied.', ge=0)]
