# generated by datamodel-codegen:
#   filename:  ApplyDdlRequest.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ApplyDdlRequest(BaseModel):
    """
    Request body for `POST /v1/schemas/{qualified}/ddl`.
    """

    ddl: Annotated[
        str, Field(description='Postgres DDL text (CREATE TABLE / CREATE INDEX / ...).')
    ]
