# generated by datamodel-codegen:
#   filename:  Envelope_QueryResponse.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, RootModel


class QueryHit(BaseModel):
    """
    One ranked hit in a [`QueryResponse`].

    Field shape mirrors `sealstack_engine::api::SearchHit` exactly so the gateway can pass engine hits through without per-field conversion.
    """

    id: Annotated[str, Field(description='Primary key of the matched record.')]
    score: Annotated[float, Field(description='Combined hybrid score.')]
    excerpt: Annotated[
        str, Field(description='Snippet of text likely to have matched.')
    ]
    record: Annotated[Any, Field(description='The full record as a JSON object.')]


class ErrorCode(
    RootModel[
        Literal['not_found']
        | Literal['unknown_schema']
        | Literal['unauthorized']
        | Literal['policy_denied']
        | Literal['invalid_argument']
        | Literal['rate_limited']
        | Literal['backend']
    ]
):
    root: Annotated[
        Literal['not_found']
        | Literal['unknown_schema']
        | Literal['unauthorized']
        | Literal['policy_denied']
        | Literal['invalid_argument']
        | Literal['rate_limited']
        | Literal['backend'],
        Field(
            description='Closed-set error code emitted by the gateway. SDKs map each variant to a typed exception class (see SDK contract spec §8).'
        ),
    ]


class QueryResponse(BaseModel):
    """
    Response data for `POST /v1/query`.

    Field order and names mirror `sealstack_engine::api::SearchResponse` exactly so the gateway can pass the engine's response through unchanged. SDK contract spec §7 documents this as the canonical wire shape.
    """

    receipt_id: Annotated[
        str, Field(description='Receipt ID; resolves via `GET /v1/receipts/{id}`.')
    ]
    results: Annotated[list[QueryHit], Field(description='Ranked hits.')]


class ErrorDetail(BaseModel):
    """
    Error detail returned in [`Envelope::error`].

    v0.3 wire shape is `{ code, message }` only. SDK contract spec §8 lists per-class typed attributes (`PolicyDeniedError.predicate`, `InvalidArgumentError.field`/`reason`, etc.) — those are populated by the SDK from response headers (`X-Request-Id` → `BackendError.request_id`; `Retry-After` → `RateLimitedError.retry_after`) or are deferred to a v0.4 envelope addition that adds an `Option<Value> details` field. The `message` field is human-readable and SDKs must not parse it.
    """

    code: Annotated[
        ErrorCode, Field(description='Closed-set error code; see [`ErrorCode`].')
    ]
    message: Annotated[
        str,
        Field(
            description='Human-readable message. Not part of the contract; do not parse.'
        ),
    ]


class EnvelopeForQueryResponse(BaseModel):
    """
    Discriminated-union response envelope. On success, `data` is `T` and `error` is `null`. On failure, `data` is `null` and `error` carries a code from [`ErrorCode`] and a human-readable message.
    """

    data: Annotated[
        QueryResponse | None,
        Field(description='Success payload, or `null` on failure.'),
    ] = None
    error: Annotated[
        ErrorDetail | None, Field(description='Error payload, or `null` on success.')
    ] = None
