# generated by datamodel-codegen:
#   filename:  ErrorCode.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field, RootModel


class ErrorCode(
    RootModel[
        Literal['not_found']
        | Literal['unknown_schema']
        | Literal['unauthorized']
        | Literal['policy_denied']
        | Literal['invalid_argument']
        | Literal['rate_limited']
        | Literal['backend']
    ]
):
    root: Annotated[
        Literal['not_found']
        | Literal['unknown_schema']
        | Literal['unauthorized']
        | Literal['policy_denied']
        | Literal['invalid_argument']
        | Literal['rate_limited']
        | Literal['backend'],
        Field(
            description='Closed-set error code emitted by the gateway. SDKs map each variant to a typed exception class (see SDK contract spec §8).',
            title='ErrorCode',
        ),
    ]
