# generated by datamodel-codegen:
#   filename:  ErrorDetail.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class ErrorCode(
    RootModel[
        Literal['not_found']
        | Literal['unknown_schema']
        | Literal['unauthorized']
        | Literal['policy_denied']
        | Literal['invalid_argument']
        | Literal['rate_limited']
        | Literal['backend']
    ]
):
    root: Annotated[
        Literal['not_found']
        | Literal['unknown_schema']
        | Literal['unauthorized']
        | Literal['policy_denied']
        | Literal['invalid_argument']
        | Literal['rate_limited']
        | Literal['backend'],
        Field(
            description='Closed-set error code emitted by the gateway. SDKs map each variant to a typed exception class (see SDK contract spec §8).'
        ),
    ]


class ErrorDetail(BaseModel):
    """
    Error detail returned in [`Envelope::error`].

    v0.3 wire shape is `{ code, message }` only. SDK contract spec §8 lists per-class typed attributes (`PolicyDeniedError.predicate`, `InvalidArgumentError.field`/`reason`, etc.) — those are populated by the SDK from response headers (`X-Request-Id` → `BackendError.request_id`; `Retry-After` → `RateLimitedError.retry_after`) or are deferred to a v0.4 envelope addition that adds an `Option<Value> details` field. The `message` field is human-readable and SDKs must not parse it.
    """

    code: Annotated[
        ErrorCode, Field(description='Closed-set error code; see [`ErrorCode`].')
    ]
    message: Annotated[
        str,
        Field(
            description='Human-readable message. Not part of the contract; do not parse.'
        ),
    ]
