# generated by datamodel-codegen:
#   filename:  HealthStatus.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class HealthStatusKind(RootModel[Literal['ok'] | Literal['starting']]):
    root: Annotated[
        Literal['ok'] | Literal['starting'],
        Field(description='Response data for `GET /healthz` and `GET /readyz`.'),
    ]


class HealthStatus(BaseModel):
    """
    Body shape for health endpoints.
    """

    status: Annotated[HealthStatusKind, Field(description='Status discriminator.')]
