# generated by datamodel-codegen:
#   filename:  ListConnectorsResponse.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ConnectorBindingWire(BaseModel):
    """
    Public projection of `sealstack_ingest::ConnectorBindingInfo` for the REST surface. Intentionally diverges in two places: renames `connector` → `kind` for SDK ergonomics, and adds an `enabled: bool` that the gateway computes from the binding's runtime state (no engine field to mirror directly). The gateway maps fields at the response boundary.
    """

    id: Annotated[str, Field(description='Binding ID.')]
    kind: Annotated[str, Field(description='Connector kind.')]
    schema_: Annotated[str, Field(alias='schema', description='Qualified schema name.')]
    enabled: Annotated[bool, Field(description='Whether the binding is enabled.')]


class ListConnectorsResponse(BaseModel):
    """
    Response data for `GET /v1/connectors`.
    """

    connectors: Annotated[
        list[ConnectorBindingWire], Field(description='Registered connector bindings.')
    ]
