# generated by datamodel-codegen:
#   filename:  QueryRequest.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """
    Request body for `POST /v1/query`.
    """

    schema_: Annotated[
        str,
        Field(
            alias='schema', description='Qualified schema name, e.g. `"examples.Doc"`.'
        ),
    ]
    query: Annotated[
        str, Field(description='Query string (natural-language or keywords).')
    ]
    top_k: Annotated[
        int | None,
        Field(description='Cap on results; `None` defaults server-side.', ge=0),
    ] = None
    filters: Annotated[
        Any | None,
        Field(
            description="Filter expression; structure depends on schema's facet declarations."
        ),
    ] = None
