# generated by datamodel-codegen:
#   filename:  QueryHit.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class QueryHit(BaseModel):
    """
    One ranked hit in a [`QueryResponse`].

    Field shape mirrors `sealstack_engine::api::SearchHit` exactly so the gateway can pass engine hits through without per-field conversion.
    """

    id: Annotated[str, Field(description='Primary key of the matched record.')]
    score: Annotated[float, Field(description='Combined hybrid score.')]
    excerpt: Annotated[
        str, Field(description='Snippet of text likely to have matched.')
    ]
    record: Annotated[Any, Field(description='The full record as a JSON object.')]
