# generated by datamodel-codegen:
#   filename:  QueryResponse.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class QueryHit(BaseModel):
    """
    One ranked hit in a [`QueryResponse`].

    Field shape mirrors `sealstack_engine::api::SearchHit` exactly so the gateway can pass engine hits through without per-field conversion.
    """

    id: Annotated[str, Field(description='Primary key of the matched record.')]
    score: Annotated[float, Field(description='Combined hybrid score.')]
    excerpt: Annotated[
        str, Field(description='Snippet of text likely to have matched.')
    ]
    record: Annotated[Any, Field(description='The full record as a JSON object.')]


class QueryResponse(BaseModel):
    """
    Response data for `POST /v1/query`.

    Field order and names mirror `sealstack_engine::api::SearchResponse` exactly so the gateway can pass the engine's response through unchanged. SDK contract spec §7 documents this as the canonical wire shape.
    """

    receipt_id: Annotated[
        str, Field(description='Receipt ID; resolves via `GET /v1/receipts/{id}`.')
    ]
    results: Annotated[list[QueryHit], Field(description='Ranked hits.')]
