# generated by datamodel-codegen:
#   filename:  ReceiptSource.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ReceiptSource(BaseModel):
    """
    One contributing source row in a [`ReceiptWire`].
    """

    chunk_id: Annotated[str, Field(description='Chunk ID this source resolves to.')]
    source_uri: Annotated[str, Field(description='Source URI for the human reader.')]
    score: Annotated[float, Field(description='Hybrid score for this contribution.')]
