# generated by datamodel-codegen:
#   filename:  ReceiptWire.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ReceiptSource(BaseModel):
    """
    One contributing source row in a [`ReceiptWire`].
    """

    chunk_id: Annotated[str, Field(description='Chunk ID this source resolves to.')]
    source_uri: Annotated[str, Field(description='Source URI for the human reader.')]
    score: Annotated[float, Field(description='Hybrid score for this contribution.')]


class ReceiptWire(BaseModel):
    """
    Public projection of `sealstack_engine::Receipt` for the REST surface. Intentionally narrower than the engine's internal Receipt: drops `qualified_schema`, `tool`, `arguments`, `policies_applied`, and `timings_ms`; renames `created_at` → `issued_at`; and surfaces `tenant` at the top level (engine has it nested in `caller`). The gateway maps fields at the response boundary.
    """

    id: Annotated[str, Field(description='Receipt ID (ULID).')]
    caller_id: Annotated[str, Field(description='Caller identity at query time.')]
    tenant: Annotated[str, Field(description='Tenant the query ran against.')]
    sources: Annotated[
        list[ReceiptSource],
        Field(description='Source records that contributed to the answer.'),
    ]
    issued_at: Annotated[str, Field(description='Issue timestamp (RFC 3339).')]
