# generated by datamodel-codegen:
#   filename:  RegisterSchemaResponse.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class RegisterSchemaResponse(BaseModel):
    """
    Response data for `POST /v1/schemas`.
    """

    qualified: Annotated[
        str, Field(description='Qualified schema name (`<namespace>.<name>`).')
    ]
