# generated by datamodel-codegen:
#   filename:  RegisterSchemaRequest.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class RegisterSchemaRequest(BaseModel):
    """
    Request body for `POST /v1/schemas`.
    """

    meta: Annotated[
        Any,
        Field(
            description='Schema metadata as emitted by `sealstack_csl::codegen`. Free-shaped here to avoid coupling api-types to the CSL crate; gateway parses into the typed `sealstack_engine::SchemaMeta` internally.'
        ),
    ]
