# generated by datamodel-codegen:
#   filename:  RegisterConnectorResponse.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class RegisterConnectorResponse(BaseModel):
    """
    Response data for `POST /v1/connectors`.
    """

    id: Annotated[
        str, Field(description='Connector binding ID (`<kind>/<qualified>`).')
    ]
