# generated by datamodel-codegen:
#   filename:  RegisterConnectorRequest.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class RegisterConnectorRequest(BaseModel):
    """
    Request body for `POST /v1/connectors`.
    """

    kind: Annotated[
        str,
        Field(
            description='Connector kind (`"local-files"`, `"github"`, `"slack"`, `"google-drive"`).'
        ),
    ]
    schema_: Annotated[
        str,
        Field(
            alias='schema', description='Qualified schema name this connector binds to.'
        ),
    ]
    config: Annotated[
        Any,
        Field(
            description='Free-shaped connector-specific config (root path, OAuth token, etc.).'
        ),
    ]
