# generated by datamodel-codegen:
#   filename:  SchemaMetaWire.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class SchemaMetaWire(BaseModel):
    """
    Response data for `GET /v1/schemas` and `GET /v1/schemas/{q}`.

    Public projection of `sealstack_engine::SchemaMeta`. Intentionally narrower than the engine's struct: drops `fields`, `relations`, `facets`, `chunked_fields`, and `context` (the SDK surface exposes schema identity + storage targets, not the full schema body). Also flattens `Option<f32> hybrid_alpha` → `f32`; the gateway substitutes the global default when the engine's value is `None`. Keeping `sealstack-api-types` free of engine deps requires the duplication; the gateway maps fields at the response boundary.
    """

    namespace: Annotated[str, Field(description='Namespace, e.g. `"examples"`.')]
    name: Annotated[str, Field(description='Schema name, e.g. `"Doc"`.')]
    version: Annotated[int, Field(description='Schema-version integer.', ge=0)]
    primary_key: Annotated[str, Field(description='Field name used as primary key.')]
    table: Annotated[str, Field(description='Postgres table name.')]
    collection: Annotated[str, Field(description='Vector store collection name.')]
    hybrid_alpha: Annotated[float, Field(description='Hybrid score blend factor.')]
