# generated by datamodel-codegen:
#   filename:  SyncConnectorResponse.json
#   timestamp: 2026-05-03T18:05:20+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class SyncConnectorResponse(BaseModel):
    """
    Response data for `POST /v1/connectors/{id}/sync`.
    """

    job_id: Annotated[str, Field(description='Job identifier for the sync run.')]
